import { log } from '@/lib/utils/logger';
import { Category, Specialty } from '@/types/category.types';

// ✅ Datos iniciales de categorías
export const DEFAULT_CATEGORIES: Omit<Category, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Construcción',
    nameEn: 'Construction',
    icon: 'building2',
    description: 'Servicios de construcción en general',
    color: '#2563EB',
    order: 1,
    isActive: true,
    metadata: {
      seoTitle: 'Servicios de Construcción | BuildLink',
      seoDescription: 'Encuentra los mejores profesionales en construcción',
      keywords: ['construcción', 'obra', 'edificación'],
    },
  },
  {
    name: 'Carpintería',
    nameEn: 'Carpentry',
    icon: 'hammer',
    description: 'Servicios de carpintería y muebles a medida',
    color: '#F59E0B',
    order: 2,
    isActive: true,
    metadata: {
      seoTitle: 'Servicios de Carpintería | BuildLink',
      seoDescription: 'Encuentra los mejores carpinteros',
      keywords: ['carpintería', 'muebles', 'madera'],
    },
  },
  {
    name: 'Techos',
    nameEn: 'Roofing',
    icon: 'home',
    description: 'Instalación y reparación de techos',
    color: '#10B981',
    order: 3,
    isActive: true,
  },
  {
    name: 'Plomería',
    nameEn: 'Plumbing',
    icon: 'droplets',
    description: 'Servicios de plomería e instalaciones hidráulicas',
    color: '#8B5CF6',
    order: 4,
    isActive: true,
  },
  {
    name: 'Jardinería',
    nameEn: 'Gardening',
    icon: 'trees',
    description: 'Servicios de jardinería y paisajismo',
    color: '#059669',
    order: 5,
    isActive: true,
  },
  {
    name: 'Electricidad',
    nameEn: 'Electrical',
    icon: 'zap',
    description: 'Servicios eléctricos e instalaciones',
    color: '#EAB308',
    order: 6,
    isActive: true,
  },
  {
    name: 'Pintura',
    nameEn: 'Painting',
    icon: 'paint-bucket',
    description: 'Servicios de pintura y decoración',
    color: '#EC4899',
    order: 7,
    isActive: true,
  },
  {
    name: 'Albañilería',
    nameEn: 'Masonry',
    icon: 'users',
    description: 'Servicios de albañilería y mampostería',
    color: '#6366F1',
    order: 8,
    isActive: true,
  },
];

// ✅ Datos iniciales de especialidades (más específicas)
export const DEFAULT_SPECIALTIES: Omit<Specialty, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // Construcción
  {
    name: 'Construcción Residencial',
    nameEn: 'Residential Construction',
    categoryId: 'construction', // ID de la categoría padre
    description: 'Construcción de viviendas y edificios residenciales',
    icon: 'home',
    color: '#2563EB',
    skills: ['cimentación', 'estructura', 'acabados'],
    certifications: ['ISO 9001'],
    experienceLevel: 'expert',
    isActive: true,
    order: 1,
  },
  {
    name: 'Construcción Comercial',
    nameEn: 'Commercial Construction',
    categoryId: 'construction',
    description: 'Construcción de locales comerciales y oficinas',
    icon: 'building',
    color: '#3B82F6',
    skills: ['estructura metálica', 'instalaciones', 'acabados comerciales'],
    experienceLevel: 'expert',
    isActive: true,
    order: 2,
  },

  // Carpintería
  {
    name: 'Muebles a Medida',
    nameEn: 'Custom Furniture',
    categoryId: 'carpentry',
    description: 'Diseño y fabricación de muebles a medida',
    icon: 'hammer',
    color: '#F59E0B',
    skills: ['diseño de muebles', 'ebanistería', 'ensamblaje'],
    experienceLevel: 'master',
    isActive: true,
    order: 1,
  },
  {
    name: 'Carpintería de Obra',
    nameEn: 'Construction Carpentry',
    categoryId: 'carpentry',
    description: 'Trabajos de carpintería en obra (estructuras, encofrados)',
    icon: 'wrench',
    color: '#D97706',
    skills: ['encofrados', 'estructuras de madera', 'andamios'],
    experienceLevel: 'intermediate',
    isActive: true,
    order: 2,
  },

  // Techos
  {
    name: 'Techos Metálicos',
    nameEn: 'Metal Roofing',
    categoryId: 'roofing',
    description: 'Instalación y reparación de techos metálicos',
    icon: 'home',
    color: '#10B981',
    skills: ['instalación de lámina', 'impermeabilización', 'acabados'],
    experienceLevel: 'intermediate',
    isActive: true,
    order: 1,
  },
  {
    name: 'Techos de Teja',
    nameEn: 'Tile Roofing',
    categoryId: 'roofing',
    description: 'Instalación y reparación de techos de teja',
    icon: 'home',
    color: '#059669',
    skills: ['colocación de teja', 'impermeabilización', 'estructura'],
    experienceLevel: 'expert',
    isActive: true,
    order: 2,
  },

  // Plomería
  {
    name: 'Instalaciones Hidráulicas',
    nameEn: 'Hydraulic Installations',
    categoryId: 'plumbing',
    description: 'Instalación y mantenimiento de sistemas hidráulicos',
    icon: 'droplets',
    color: '#8B5CF6',
    skills: ['tuberías', 'bombas', 'válvulas'],
    certifications: ['Certificación hidráulica'],
    experienceLevel: 'expert',
    isActive: true,
    order: 1,
  },
  {
    name: 'Reparaciones de Fontanería',
    nameEn: 'Plumbing Repairs',
    categoryId: 'plumbing',
    description: 'Reparación de fugas y problemas de fontanería',
    icon: 'wrench',
    color: '#7C3AED',
    skills: ['detección de fugas', 'reparación de tuberías', 'instalación de sanitarios'],
    experienceLevel: 'intermediate',
    isActive: true,
    order: 2,
  },

  // Jardinería
  {
    name: 'Diseño de Jardines',
    nameEn: 'Garden Design',
    categoryId: 'gardening',
    description: 'Diseño y creación de jardines',
    icon: 'trees',
    color: '#059669',
    skills: ['diseño paisajístico', 'plantación', 'riego'],
    experienceLevel: 'expert',
    isActive: true,
    order: 1,
  },
  {
    name: 'Mantenimiento de Jardines',
    nameEn: 'Garden Maintenance',
    categoryId: 'gardening',
    description: 'Mantenimiento y cuidado de jardines',
    icon: 'scissors',
    color: '#10B981',
    skills: ['poda', 'abonado', 'control de plagas'],
    experienceLevel: 'entry',
    isActive: true,
    order: 2,
  },
];
